

GET http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/284512de-a2eb-4262-a291-5b14832f9d96

###

POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

PUT http://localhost:3000/tasks/66d85657-02b6-43d9-a4d1-e4996c78da4f HTTP/1.1
content-type: application/json

{
    "title": "sample2",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT",
    "tag": "sample"
}

###

GET http://localhost:3000/tasks/aa7811ca-66f2-4451-bfad-d79e466f1c6a/check HTTP/1.1

###

DELETE http://localhost:3000/tasks/66d85657-02b6-43d9-a4d1-e4996c78da4f HTTP/1.1
content-type: application/json








###


GET http://localhost:3000/tags

###

GET http://localhost:3000/tags/284512de-a2eb-4262-a291-5b14832f9d96

###

POST http://localhost:3000/tags HTTP/1.1
content-type: application/json

{
    "title": "Tag",
    "color": "#7159c1"
}

###

PUT http://localhost:3000/tags/284512de-a2eb-4262-a291-5b14832f9d96 HTTP/1.1
content-type: application/json

{
    "title": "sample2",
    "description": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

DELETE http://localhost:3000/tags/7bc8e46e-a82e-4e28-9b32-fceda4979973 HTTP/1.1
content-type: application/json